export const FLAVOR_SYNONYMS: Record<string, string[]> = {
  // Sabores
  'fresa': ['strawberry'],
  'frutilla': ['strawberry'],
  'strawberry': ['fresa', 'frutilla'],
  'menta': ['mint'],
  'mint': ['menta'],
  'sandia': ['watermelon'],
  'sandía': ['watermelon'],
  'watermelon': ['sandia'],
  'uva': ['grape'],
  'grape': ['uva'],
  'piña': ['pineapple'],
  'pina': ['pineapple'],
  'pineapple': ['piña'],
  'durazno': ['peach'],
  'peach': ['durazno'],
  'manzana': ['apple'],
  'apple': ['manzana'],
  'cereza': ['cherry'],
  'cherry': ['cereza'],
  'limon': ['lemon'],
  'limón': ['lemon'],
  'lemon': ['limon'],
  'coco': ['coconut'],
  'coconut': ['coco'],
  'chicle': ['bubblegum'],
  'bubblegum': ['chicle'],
  'mora': ['berry', 'blueberry'],
  'moras': ['berry', 'blueberry'],
  'arandano': ['blueberry'],
  'arándano': ['blueberry'],
  'blueberry': ['arandano', 'mora'],
  // Colores
  'negro': ['black'],
  'black': ['negro'],
  'blanco': ['white'],
  'white': ['blanco'],
  'rojo': ['red'],
  'red': ['rojo'],
  'azul': ['blue'],
  'blue': ['azul'],
  'verde': ['green'],
  'green': ['verde'],
  'morado': ['purple'],
  'purple': ['morado'],
  'plomo': ['grey', 'gray', 'silver'],
  'gris': ['grey', 'gray', 'silver'],
  'plateado': ['silver'],
  'dorado': ['gold'],
  'gold': ['dorado'],
  // Términos generales
  'calada': ['puffs'],
  'caladas': ['puffs'],
  'puffs': ['calada', 'caladas'],
};
